# Generated by Django 4.0.5 on 2022-06-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dept', models.TextField()),
                ('number', models.IntegerField()),
                ('name', models.TextField()),
                ('prof', models.TextField()),
                ('dept_and_number', models.TextField()),
                ('prereqs', models.TextField()),
                ('start_time', models.TextField()),
                ('end_time', models.TextField()),
                ('offered', models.TextField()),
                ('median', models.TextField()),
                ('median_semester', models.TextField()),
                ('median_prof', models.TextField()),
                ('prof_diff', models.TextField()),
                ('prof_rating', models.TextField()),
                ('prof_num_rating', models.TextField()),
                ('class_diff', models.TextField()),
                ('class_rating', models.TextField()),
                ('class_workload', models.TextField()),
            ],
            options={
                'ordering': ('median',),
            },
        ),
    ]
